---
booktitle: 'Proceedings of the Twelveth International Symposium on Imprecise Probability:
  Theories and Applications'
shortname: ISIPTA
sections:
- name: Preface
  title: Preface
- name: Full Papers
  title: Full Papers
- name: Short Papers
  title: Short Papers
year: '2021'
volume: '147'
start: 2021-07-06
end: 2021-07-09
published: 2021-08-18
url: https://proceedings.mlr.press
conference_number: '12'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ISIPTA2021
month: 0
cycles: false
bibtex_editor: Cano, Andr\'es and De Bock, Jasper and Miranda, Enrique and Moral,
  Seraf\'{\i}n
editor:
- given: Andrés
  family: Cano
- given: Jasper
  family: De Bock
- given: Enrique
  family: Miranda
- given: Serafı́n
  family: Moral
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Twelveth International Symposium on Imprecise Probability: Theories and Applications
    Held in University of Granada, Granada, Spain on 06-09 July 2021

  Published as Volume 147 by the Proceedings of Machine Learning Research on 18 August 2021.

  Volume Edited by:
    Andrés Cano
    Jasper De Bock
    Enrique Miranda
    Serafı́n Moral

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 06--09 Jul
author:
  name: PMLR
baseurl: "/v147"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v147
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v147
email: ''
conference:
  name: 'International Symposium on Imprecise Probability: Theories and Applications'
  url:
  location: University of Granada, Granada, Spain
  dates:
  - 2021-07-06
  - 2021-07-07
  - 2021-07-08
  - 2021-07-09
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v147/isipta2021.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v147/isipta2021.bib
